# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='labels',
            field=models.ManyToManyField(blank=True, to='notes.Label'),
        ),
    ]
